#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
    CREATE TABLE IF NOT EXISTS calcul (
	  guid VARCHAR ( 50 )  NOT NULL PRIMARY KEY,
	status VARCHAR ( 50 )  NULL,
	date_debut VARCHAR ( 50 )  NOT NULL,
	date_fin VARCHAR ( 50 )   NULL,
	montant REAL,
	resultat REAL
	);
  COMMIT;
EOSQL